### ISSUE TITLE
Default Blood

### ISSUE THREAD

**Issue by Fortist** [CyclopsMC/FluidConverters#14]
To test this mod out I decided to try the default blood config you added and I found that nothing I do can change the converter to output, and Im not even sure things are being inputed.
I have two of the three bloods, Tcon's and Blood Magics.

I rightclick the converters with a bucket of each and nothing happens or changes.

Im going to make a custom config and see if that doesnt work as well, and enable the lava aqua one to test.

Also, I do not use buildcrap, so I wonder if its also the pipes?

UPDAT: It seems like its only the blood one not working, however, this experience one I made is not registering.
Also, when I comment out or straight up delete the blood.json, it comes back.

**Comment by rubensworks** [comment]
Can you give me the version of this mod, TCon and BM you are using?
The converter will always accept fluids (blood) from the given fluid group, for marking a side as output you have to right click with a fluid converter from that group (blood in your case) on a side, for example with a Bucket of Life Essence, this should visually show the Life Essence fluid on that side.

I'm not having any issues with it myself, maybe you can send me some screenshots with a detailed explanation of what you are trying to do? And which pipes are you using then?

**Comment by Fortist** [comment]
Latest Tcon and BM. Im in my creative world and I have a bucket of life essence from BM, and it didnt register Tcon's bucket o blood for the recipe, but mariculture's bucket of blood.
I took all three and right clicked on every side to no effect.
Also, Im using Mekanism's and Ender Io's, which works with the aqua lava one, actually.

And it turned out I missed a comma in the config for my Experience one, so that works now.
The blood one doesnt really matter to me, actually So, yeah
![javaw 2014-11-12 09-52-44-87](https://cloud.githubusercontent.com/assets/5784537/5012157/d32df990-6a51-11e4-8790-83fa827bc5c2.png)

**Comment by rubensworks** [comment]
Ok, good to hear it's working for you.
I'll leave this issue open for now, so I can see what the problem could be with the blood converter.
And thanks for reporting.
