### ISSUE TITLE
Don't reinvent the wheel

### ISSUE THREAD

**Issue by immortaleeb** [CyclopsMC/FluidConverters#18]
CyclopsCore/Forge has several features built in that save a lot of the work I'm doing manually at the moment.
In particular look at the following things:
- [x] `ItemBlockNBT` saves NBT to tile entities automatically.
- [ ] Parsing of json files using GSON could probably be done prettier.

**Comment by rubensworks** [comment]
I assume this is never going to happen anymore, so I'm closing this one, the current code is fine as it is.
