### ISSUE TITLE
Add support for JEI

### ISSUE THREAD

**Issue by immortaleeb** [CyclopsMC/FluidConverters#23]
Didn't you read the title?
What more do you expect here?

**Comment by Runesmacher** [comment]
First implementation made, comments are welcome:
![image](https://cloud.githubusercontent.com/assets/979451/21951944/065bed42-da10-11e6-8895-10281b6075a9.png)

**Comment by rubensworks** [comment]
@Runesmacher Looks good!

Perhaps you could add the conversion rate explicitly above or below the arrow as well.

If it's possible, you may also want to use the NBT-sensitive variant of the fluid converter block on the top. If it's not possible, we may have to convince Mezz to add support for that, I'm sure he'd be open for it.

**Comment by Runesmacher** [comment]
Further implemented the integration, still need to split the converters, working on that
https://github.com/Runesmacher/FluidConverters/tree/AddJEIIntegration

**Comment by rubensworks** [comment]
Implemented in d0a156230009346a53d242eea5cbed89cf6c262e by @Runesmacher
