### ISSUE TITLE
Crashed my server on load

### ISSUE THREAD

**Issue by scalda** [CyclopsMC/FluidConverters#3]
Hi, 

I installed this mod earlier after getting the link from reddit and it has caused a crash on my server

here is the link to the pastebin for the crash report http://pastebin.com/p6FiVvWX

I'm sure its something i have done wrong but i cant see what it could

Thanks in advance

Scalda

**Comment by rubensworks** [comment]
It's not something you have done wrong, just a mistake on my end.
Will fix this asap.

**Comment by scalda** [comment]
Ok glad it could help you

**Comment by rubensworks** [comment]
Version 1.0.1 is available on curse forge.

**Comment by scalda** [comment]
ok cheers now running server with updated file
