### ISSUE TITLE
Evilcraft blood to Life essence

### ISSUE THREAD

**Issue by Caopr** [CyclopsMC/FluidConverters#35]
IM unable to convert anything from the fluid converter. It will fill with blood but not process it. Ive even clicked the wanted output side with a bucket of life essence and nothing happens. The buffer of the block is full.
Unable to even convert life essence into evilcraft blood when I do right click a side with the appropriete blood bucket all I get  in my chat is

"fluid group:Blood to Life
 fluid group:Blood to Life"

from a single click

Also the auto config for blood didint even show Life essence ingame for the converter until I changed the name "life essence" to "lifeessence"  which caused the recipe to show. might be worth to change that

Heres my blood.json

{
  "groupId": "blood",
  "groupName": "Blood to Life",
  "fluidElements": [
    {
      "fluidName": "evilcraftblood",
      "value": 1.0
    },
    {
      "fluidName": "lifeessence",
      "value": 2.0
    }
  ],
  "lossRatio": 0.5,
  "hasRecipe": true,
  "hasDefaultRecipe": true
}

**Comment by rubensworks** [comment]
What mod and mc version are you using?

**Comment by Caopr** [comment]
Minecraft 1.11.2 Evilcraft

**Comment by Caopr** [comment]
Minecraft 1.11.2

**Comment by Caopr** [comment]
Minecraft 1.11.2 
EvilCraft-1.11.2-0.10.27.jar      /     -Where the blood is from
BloodMagic-1.11-2.1.10-79.jar   /        -Where the Life Essence is from
FluidConverters-1.11.2-2.2.1.jar

**Comment by Caopr** [comment]
Thank you for your help with both issues btw :3

**Comment by rubensworks** [comment]
Np, if it's broken, I have to fix it. Thanks for reporting :-)
