### ISSUE TITLE
[1.12] Default recipe missing 

### ISSUE THREAD

**Issue by CplPibald** [CyclopsMC/FluidConverters#38]
FluidConverters-1.12-2.2.6

Using default config for blood.json with EvilCraft and Tinker's Construct loaded.

```
  ],
  "hasRecipe": true,
  "hasDefaultRecipe": true
}
```

No recipe in JEI.  Assembling the default recipe on the wiki using a blood bucket from either mod does not produce a recipe output.

-----

Aside: The example configs `blood.json` and `example.json.template` contain an element `hasRecipe`, which looks like it was removed [here](https://github.com/CyclopsMC/FluidConverters/commit/d22deadc65ad5eca7fc7eaf88346140db622697a).  Can you update the examples to the newest config format?  Thanks.

**Comment by CplPibald** [comment]
I was also unable to get a custom recipe working.  The log contained this error.
```
[main/ERROR] [FluidConverters/]: Could not find the predefined item for key 'fluidconverters:fluidconverter_blood'.
```

**Comment by rubensworks** [comment]
New release with a fix for this should appear on CurseForge soon.
