### ISSUE TITLE
[1.12.2] Bug: Wrong behaviour?

### ISSUE THREAD

**Issue by joselitosn** [CyclopsMC/FluidConverters#40]
Using the same setup seen on the Curse page screenshots with only Buildcraft 7.99.13 and recipe lavawater.

1) If you pump Lava from one side you need to have a Bucket of Water to mark the output? That seems counterintuitive, if i need to convert from two different fluids, most likely I don't have the output one at hand.

2) If you pump Lava and mark Lava as an output, you get Lava? Why? It should not output anything. The conversion is between Lava and Water and vice versa.

3) You have to mark either the up or down faces to get any output, even if the output is in any other side.

4) Not necesserily a bug, but you can't get more than one output at the same time. It should be able to handle more than one output with a round-robin algorithm.

5) Possibly a suggestion, can you include the rate of the conversion per recipe?

Current Versions:
- This mod: 2.2.8
- CyclopsCore: 0.11.0
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.1.2562

**Comment by rubensworks** [comment]
> 1) If you pump Lava from one side you need to have a Bucket of Water to mark the output? That seems counterintuitive, if i need to convert from two different fluids, most likely I don't have the output one at hand.

That's just how it works, call it a balancing decision.

> 2) If you pump Lava and mark Lava as an output, you get Lava? Why? It should not output anything. The conversion is between Lava and Water and vice versa.

This behaviour can be useful in some cases. If you don't like it, just don't mark an output with Lava.

> 3) You have to mark either the up or down faces to get any output, even if the output is in any other side.

Not sure what you mean. Is this a bug? If so, please report this as a separate issue.

> 4) Not necesserily a bug, but you can't get more than one output at the same time. It should be able to handle more than one output with a round-robin algorithm.

True, that's how it works atm. Feel free to open a feature request. I might be able to look into this somewhere in the future.

> 5) Possibly a suggestion, can you include the rate of the conversion per recipe?

That could be done, but open it as a separate issue please. That makes it easier for me to track work that needs to be done.
