### ISSUE TITLE
Doesn't work after Forge/Java update

### ISSUE THREAD

**Issue by onyxism** [CyclopsMC/FluidConverters#41]
#### Issue type:
- :bug: Bug
____
#### Short description:
After updating to forge1.12.2-14.23.2.2625 fluid converters stopped working.

#### Expected behaviour:
Source fluid travels through the FluidConverter and new fluid travels out of it.

#### Actual behaviour:
Nothing happens.

#### Steps to reproduce the problem:

1. Add simple recipe to the config\fluidcoverters folder
     _e.g._ [https://pastebin.com/TW5tkti6](https://pastebin.com/TW5tkti6)

2. Setup FluidConverter block with water on top and lava on the side and with some type of fluid transport. 
     _Integrated Dyanmics_ - [https://i.imgur.com/RsRIydR.png](https://i.imgur.com/RsRIydR.png) 
     _Thermal Expansion_ - [https://i.imgur.com/8baFbAW.png](https://i.imgur.com/8baFbAW.png)

3. Observe nothing happens.

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod:  1.12.2-2.2.8
- CyclopsCore: 1.12.2-0.11.5
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.2.2625
- Java: 8 update 161 (build 1.8.0_161-b12)
#### Log file:
_fml-client-latest.log_ - [https://pastebin.com/KS0dnCE5](https://pastebin.com/KS0dnCE5)
_latest.log_ - [https://pastebin.com/VMi7EdHa](https://pastebin.com/VMi7EdHa)

**Comment by rubensworks** [comment]
Your setup is invalid, you have to unbind the input side fluid.

This was a recent (undocumented) change, so that's on me, sorry.

I have updated the curseforge page with this new information.

**Comment by onyxism** [comment]
I've tried with un-binded input side, and i still haven't gotten it to work. is there anything else you can suggest?

**Comment by rubensworks** [comment]
So only the lava-side is configured and attached to a fluid output?

You mentioned that this used to work in an earlier Forge version, could you try downgrading to that version to see if it changes anything?

**Comment by onyxism** [comment]
After doing a lot of testing, it was the version of java i used. the default minecraft one works. the one that i installed from the java.com for some reason doesn't work. i used that java for other things i figured i'd use it in minecraft since it's supposedly better.

**Comment by rubensworks** [comment]
> After doing a lot of testing, it was the version of java i used.

I strongly doubt that this is a Java issue...

But it's working now for you? Can this be closed then?

**Comment by onyxism** [comment]
Sure, you can close it. The last thing that i did is i just did a clean reinstall of very thing. so it might have been something else than java. i just know it's working out now.
