### ISSUE TITLE
You have to mark either the north and west faces to get any output

### ISSUE THREAD

**Issue by Luicuelo** [CyclopsMC/FluidConverters#43]
#### Issue type:

- :bug: Bug

____

#### Short description:

The fluid input is from east.
You have to mark either the north and west faces to get  north output

if you dont mark the west face there is not output to north. (the opossite face, west , must be marked).

____

#### Versions:

- This mod:  FluidConverters-1.12.2-2.2.10
- Minecraft:  1.12.2
- Forge:  forge-1.12.2-14.23.5.2808

![Captura](https://user-images.githubusercontent.com/30816963/55037178-2b2aa700-501d-11e9-8c2b-efa458740bb0.PNG)

**Comment by rubensworks** [comment]
Your description is a bit confusing. Can you describe a step-by-step guide to reproduce your problem?

**Comment by Luicuelo** [comment]
Put  the source connected to east side
Mark north face with fluid
put the Destiny connected to north face for output

**is not working**, nothing happends

now , Mark west face with fluid and the fluid begins to pass.

So you need to mark two sides (the nort side , and then west side) to work
Seems the opossite side of the source must to be marked.

**Comment by rubensworks** [comment]
Thanks for the info, I will look into it soon.
