### ISSUE TITLE
[1.7.10] What Should I do to make fluid converters work with Mekanism Liquids

### ISSUE THREAD

**Issue by whatsapp2** [CyclopsMC/FluidConverters#44]
#### Issue type:

- :question: Question
What Should I do to fix this fluid problem?
____

#### Question:

I've been playing with the latest version of Fluid Converters for 1.7.10. I use this mod to unify some common liquids, for example chlorine (Reactorcraft) and chlorine (Minechem), but when I try to add Liquid Chlorine (Mekanism) as the output in the fluid converter, nothing happens. 
Liquid doesn't show up, I tried using different fluid handlers from various mods (Tanks by Mekanism, Tank by Thermal Expansion, Canisters by Pressurized Tubes, Reservoirs by RotaryCraft, Tanks by Buildcraft, Tanks by Galacticraft, Universal Cell by IC2 Exp...). I figured that maybe it is because Mekanism doesn't provide a vanilla bucket and also a placeable fluid. OmniFluids mod does this two things, it adds placeable fluids and a omnibucket. But even with this two features implemented, output selection in the fluid converter will not work. 

Strange thing is that when you pump in the Mekanism liquids to obtain some other fluid, the converter will work:

![2019-10-13_19 16 58](https://user-images.githubusercontent.com/25994176/66724639-131a4980-edee-11e9-84c5-413ccdb9ca00.png)

But it will not work viceversa

**Comment by rubensworks** [comment]
Oof, 1.7.10, not sure I'll be able to help with that. I'm working on 1.14.4 right now.

But I assume Mekanism is just doing funky things with fluids, as their gases don't properly implement the fluids API.

**Comment by rubensworks** [comment]
Considering a wont-fix.
