### ISSUE TITLE
Steam from different mods

### ISSUE THREAD

**Issue by raymondbh** [CyclopsMC/FluidConverters#45]
#### Issue type:

- :question: Question

____

#### Question:
I am trying to make a converter from IC2's steam and superheated steam to Railcraft steam (or vice versa). Is this possible? 
My json look like this: https://pastebin.com/XW1nBhXN
The log says this: https://pastebin.com/Au6KJkmS

When I am ingame I can give myself the items with the command:
/give player railcraft:steam (this works for all the steams in the json...)

**Comment by rubensworks** [comment]
The log indicates that you are using the wrong fluid name (you are using item names).

You can find out about all available fluid names using the `\listfluids` command that this mod adds.

**Comment by raymondbh** [comment]
nvm, I got it now, thank you :-)
