### ISSUE TITLE
No "/getfluids" command

### ISSUE THREAD

**Issue by scalda** [CyclopsMC/FluidConverters#6]
As the title suggests, it doesn't show in the the server help or recognizes the command at all.

sorry if this is bothering you

Scalda

**Comment by rubensworks** [comment]
This command is only available client-side, because it uses the tab-completion to scroll through all the available fluid names. But I might add a similar command server-side if the need exists.
And thanks for the reports, since this mod is still in beta I welcome all the feedback I can get :)
